use_frameworks!

target 'ScrubbedPhotoViewer_Example' do
  pod 'ScrubbedPhotoViewer', :path => '../'

  target 'ScrubbedPhotoViewer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
