
use_frameworks!
inhibit_all_warnings!

platform :ios, '9.0'


def core_pods
	pod 'ScrubbedPhotoViewer', :path => '../'
end

target 'ScrubbedPhotoViewer_Example' do
	core_pods
end

target 'ScrubbedPhotoViewer_Tests' do
	core_pods
#	pod 'FBSnapshotTestCase' , '~> 2.1.4'
end
